name: build
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build_and_test:
    name: rmf_simulation
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      # NOTE: Avoid adding comments in the packages lines, this can break some of the called scripts in github actions
      packages: |
        rmf_building_sim_gz_plugins
        rmf_robot_sim_common
        rmf_robot_sim_gz_plugins
      dist-matrix: '[{"ros_distribution": "rolling", "ubuntu_distribution": "noble"}]'
