name: tsan
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tsan:
    name: tsan
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-latest
    steps:
      - name: deps
        uses: ros-tooling/setup-ros@v0.4
        with:
          required-ros-distributions: humble
      - name: install_clang
        run: sudo apt update && sudo apt install -y clang clang-tools lld
      - name: tsan_build_test
        uses: ros-tooling/action-ros-ci@v0.2
        id: tsan_build_test
        env:
          CC: clang
          CXX: clang++
        with:
          target-ros2-distro: humble
          # build all packages listed in the meta package
          package-name: |
            rmf_building_sim_common
            rmf_building_sim_gz_classic_plugins
            rmf_building_sim_gz_plugins
            rmf_robot_sim_common
            rmf_robot_sim_gz_classic_plugins
            rmf_robot_sim_gz_plugins
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/open-rmf/rmf/main/rmf.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["tsan", "lld"],
                "cmake-args": ["-DCMAKE_BUILD_TYPE=Debug"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: upload_test_stream
        uses: actions/upload-artifact@v2
        with:
          name: colcon-test-logs
          path: ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log
        if: always()
