name: tsan
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tsan:
    name: tsan
    uses: open-rmf/rmf_ci_templates/.github/workflows/reusable_build.yaml@main
    with:
      # NOTE: Avoid adding comments in the packages lines, this can break some of the called scripts in github actions
      packages: |
        rmf_building_sim_gz_plugins
        rmf_robot_sim_common
        rmf_robot_sim_gz_plugins
      # Foxy and Galactic are deprecated for this package because of the dependency to old gazebo packages
      dist-matrix: '[{"ros_distribution": "rolling", "ubuntu_distribution": "noble"}]'
      mixin: tsan
