name: tsan
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tsan:
    name: tsan
    runs-on: ubuntu-20.04
    steps:
      - name: deps
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: foxy
      - name: tsan_build_test
        uses: ros-tooling/action-ros-ci@v0.2
        id: tsan_build_test
        env:
          CC: clang
          CXX: clang++
        with:
          target-ros2-distro: foxy
          # build all packages listed in the meta package
          package-name: |
            rmf_building_sim_common
            rmf_building_sim_gazebo_plugins
            rmf_building_sim_ignition_plugins
            rmf_robot_sim_common
            rmf_robot_sim_gazebo_plugins
            rmf_robot_sim_ignition_plugins
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/open-rmf/rmf/main/rmf.repos
          colcon-defaults: |
            {
              "build": {
                "mixin": ["tsan"],
                "cmake-args": ["-DCMAKE_BUILD_TYPE=Debug"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - name: upload_test_stream
        uses: actions/upload-artifact@v2
        with:
          name: colcon-test-logs
          path: |
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_building_sim_common/streams.log
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_building_sim_gazebo_plugins/streams.log
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_building_sim_ignition_plugins/streams.log
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_robot_sim_common/streams.log
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_robot_sim_gazebo_plugins/streams.log
            ${{ steps.tsan_build_test.outputs.ros-workspace-directory-name }}/log/latest_test/rmf_robot_sim_ignition_plugins/streams.log
        if: always()

